# Generated by Django 5.1.6 on 2025-04-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='vaform',
            name='document',
        ),
        migrations.AddField(
            model_name='vaform',
            name='dd4document',
            field=models.FileField(blank=True, null=True, upload_to='va_documents/'),
        ),
        migrations.AddField(
            model_name='vaform',
            name='other_document',
            field=models.FileField(blank=True, null=True, upload_to='other_documents/'),
        ),
    ]
