# Generated by Django 5.1.6 on 2025-04-25 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contact_remove_vaform_document_vaform_dd4document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaform',
            name='dd4document',
        ),
        migrations.RemoveField(
            model_name='vaform',
            name='other_document',
        ),
        migrations.AddField(
            model_name='vaform',
            name='fax_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('dd4', 'DD4 Document'), ('other', 'Other Document')], max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('va_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mainapp.vaform')),
            ],
        ),
    ]
