# Generated by Django 5.1.6 on 2025-04-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_otherdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdocument',
            name='document_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
